blank_issues_enabled: true
contact_links:
  - name: BTQ Core Security Policy
    url: https://github.com/btq/btq/blob/master/SECURITY.md
    about: View security policy
  - name: BTQ Core Developers
    url: https://btqcore.org
    about: BTQ Core homepage
